language: ruby
rvm:
  - 2.1.2
before_script:
  - psql -c 'create database secret_app_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
bundler_args: --binstubs=./bundler_stubs