development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: secret_app_dev
  pool: 5
  username: postgres
  password: 

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: secret_app_test
  pool: 5
  username: postgres
  password: 