development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: peer_street_dev
  pool: 5
  username: postgres
  password: 

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: peer_street_test
  pool: 5
  username: postgres
  password: 