development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: peer_street_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: peer_street_test
  pool: 5
  username: root
  password:

