# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a79c9f971fde681f49f1b594f866bd59ff9cdbc58c97faa892140adb11d9c7471694a6890adb0d0055d58905f6734b468c9e68af53dfb893638ec77bbe3fa005
  send_grid_pass: <%= ENV["SEND_GRID_PASS"] %>
  secret_pass: aewsaews
  devise_key: bb3eeef40cb9e39ae5e0c4ba2202d4910c98fc43073c07015b75816ef326e40acdc53cd8de5f3e33d32ebf0dccccef3ba8cf64df1ee9d2ce5d0ad3a822a0f2a2

test:
  secret_key_base: 57070696fdef06ddc383cc6d98a49825a70badcf9428fa75ce43362f844bfd1e219259f5d0fb013eaac84f4f900347a05b2fd2e7cc3802c9bbd9351525573f18
  send_grid_pass: <%= ENV["SEND_GRID_PASS"] %>
  secret_pass: aewsaews
  devise_key: bb3eeef40cb9e39ae5e0c4ba2202d4910c98fc43073c07015b75816ef326e40acdc53cd8de5f3e33d32ebf0dccccef3ba8cf64df1ee9d2ce5d0ad3a822a0f2a2

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  send_grid_pass: <%= ENV["SEND_GRID_PASS"] %>
  secret_pass: <%= ENV["SECRET_PASS"] %>
  devise_key: <%= ENV["DEVISE_KEY"] %>